language: node_js
node_js:
- '6'
cache: yarn
script: npm run lint
notifications:
  email: false
  slack:
    secure: lk5K/dwlWKGVaJVLeL2m54veAP1rsJVXLmQDRxDByz5YpzSGrtgnxge2ioyqoy2BNRGztKRh9aMqKY5ACiIi9gU+R+O8ts9x4D6S9qFlGq9ZJ5oqeaEEyLelNmWc2SnSyCzhkILhAh4yi+4niuP7zxgFkes5/s6Tn0ysW4mY+unpdO2Oqd9KONpdT6ByLrp7uIVLzEjGVEdjb9MqFXMz347R2+gwlMfTyoyO3v5jkgCzMCrUVaFI9bSmycd/1BQl9BtdSbvUKcDplFk1N0xsQwKsAVvCaTPiZJwXCSSweCoN/LFWmC98TKoUThdcZg1+BHX/PwZaQakdPivy5SNHOpLtiJLrSLuVYA0BEnLZ+IOf/khfsYFgPryN3C9lhYf401OzMAZFAeOLmOnucYWggRLmo3S4eFCnf5byhEoef6AQ71hENfkpVr+5Pk04jifgFTLbyxXlLhJobb3luOa9GjMQ5KpbrXCi+4OARiKHcIZhJJyfDuKWwK89sltYqPlJVM62xI2aZ8dw58R7j922hc0bJIKuIW3AZFcTlJ2MIBMNDBCcvPtryg1C9ZE/nflbYGTO2itLzbP2e4IvBS5oz/qCogmiZxe+7E53b7w6YlFoDg0FQBg5RthRrWOrnMU1oEYOIAoQFkkuV7g6BEcofSH3nxQeLasGudVw0T8fCXU=
deploy:
  provider: npm
  email: adam@fransvilhlem.com
  api_key:
    secure: eTURN/fNfS0fo8e+iHT4JQ4MEWAdP+gQ+XRCmdoLoDwYjh2xRr6CMSgGdBGp1pKXaSY1mvdgE01bbIovzYbVOFbuKthfTAiFG7c9Bz+EMcSSHfu0FyvNSpJoZWABydxo38wiYSspXBPDTPNI1N3U4nTZh8SYZqjKaSf6G6Gz2O5HHzUrq1AqFyzFlKdLv4iFr+bGQomgdJQxHqnr8u5fqhSWF1oNlQOzxomYA9UETTxT9v7ubTUmHmjQcNJSkP2u1Snq1nWuPPOUD3uWtk37mFNsnw/oeDkF5eeDfE5QuCzxHneJ08htCZB40VOriHcdBAy9+CmJr1aA8titjym2P8uvf+/FdoGPZExcYf6WT5KuJ65WLmpTUxRch0AQQ6a1tVAzvRU8cmR494uOxeEWpufY5AiTPs9Ib2AXh2WGFD5C4C9IxxV1SY56pYuifWiBi7QiEIlWu9AdGnc4nqLVTXGufIytjKynMLfB4EmPO5g6CwLMOYOaHCVFx9sy2Wglj7JM60yj2T6DA/mIksBdETUuTilUzySWBVzlqLPDlArJTpWOA9VpNkDZfUcpoTvXy5tZrKOEuGetws/nKDQokBoWA2E7J9SGAzpeCPqpqDo9CHNO+j6lskQgwWfTnT9xJhnGR+3h6wSoyafpzqhT9XpDODB46QRz1uZpRV1abSg=
  on:
    tags: true
    branch: master
    repo: adambrgmn/stylelint-config-fransvilhelm-order
